version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_flowise
    restart: always
    environment:
      POSTGRES_USER: flowise
      POSTGRES_PASSWORD: flowise123
      POSTGRES_DB: flowisedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise_app
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=flowisedb
      - DATABASE_USER=flowise
      - DATABASE_PASSWORD=flowise123
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin123
    ports:
      - "3000:3000"
    volumes:
      - flowise_data:/root/.flowise

volumes:
  postgres_data:
  flowise_data:
